# frozen_string_literal: true

RSpec.describe WbBotModelFallback::ForeignReasoning do
  fab!(:primary) { Fabricate(:llm_model, name: "primary-model") }
  fab!(:fallback) { Fabricate(:llm_model, name: "fallback-model") }
  fab!(:user)
  fab!(:bot_user, :user)
  fab!(:pm) do
    Fabricate(
      :private_message_topic,
      user: user,
      topic_allowed_users: [
        Fabricate.build(:topic_allowed_user, user: user),
        Fabricate.build(:topic_allowed_user, user: bot_user),
      ],
    )
  end
  fab!(:first_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 1,
      raw: "Первый вопрос",
      created_at: 10.minutes.ago,
    )
  end
  fab!(:primary_answer) do
    Fabricate(
      :post,
      topic: pm,
      user: bot_user,
      post_number: 2,
      raw: "Ответ основной",
      created_at: 9.minutes.ago,
    )
  end
  fab!(:second_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 3,
      raw: "Второй вопрос",
      created_at: 8.minutes.ago,
    )
  end
  fab!(:fallback_answer) do
    Fabricate(
      :post,
      topic: pm,
      user: bot_user,
      post_number: 4,
      raw: "Ответ запасной",
      created_at: 7.minutes.ago,
    )
  end
  fab!(:third_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 5,
      raw: "Третий вопрос",
      created_at: 6.minutes.ago,
    )
  end

  def remember_model(post, model, text, encrypted)
    post.custom_fields[DiscourseAi::AiBot::POST_AI_LLM_MODEL_ID_FIELD] = model.id
    post.save_custom_fields
    PostCustomPrompt.create!(
      post: post,
      custom_prompt: [
        [
          text,
          bot_user.username,
          nil,
          nil,
          {
            "message" => "рассуждение",
            "provider_info" => {
              "open_ai_responses" => {
                "reasoning_id" => "rs_#{encrypted}",
                "encrypted_content" => encrypted,
              },
            },
          },
        ],
      ],
    )
  end

  before do
    enable_current_plugin
    remember_model(primary_answer, primary, "Ответ основной", "enc-primary")
    remember_model(fallback_answer, fallback, "Ответ запасной", "enc-fallback")
  end

  def history
    DiscourseAi::Completions::PromptMessagesBuilder.messages_from_post(
      third_question,
      max_posts: 10,
      bot_usernames: [bot_user.username],
      include_uploads: false,
    )
  end

  def encrypted(messages)
    messages.filter_map do |message|
      message.dig(:thinking_provider_info, :open_ai_responses, :encrypted_content)
    end
  end

  it "keeps all reasoning outside of a bot reply" do
    expect(encrypted(history)).to contain_exactly("enc-primary", "enc-fallback")
  end

  it "drops reasoning of posts generated by the primary model when answering with the fallback" do
    expect(encrypted(described_class.with_model(fallback.id) { history })).to eq(["enc-fallback"])
  end

  it "drops reasoning of the fallback model when answering with the primary again" do
    expect(encrypted(described_class.with_model(primary.id) { history })).to eq(["enc-primary"])
  end

  it "keeps the text of the answers whose reasoning was dropped" do
    text =
      described_class.with_model(fallback.id) { history }.map { |m| m[:content].to_s }.join("\n")
    expect(text).to include("Ответ основной", "Ответ запасной")
  end

  it "restores the thread state after the block" do
    described_class.with_model(fallback.id) { history }
    expect(Thread.current[described_class::CURRENT_MODEL]).to be_nil
    expect(Thread.current[described_class::FOREIGN_STAMPS]).to be_nil
  end
end
