# frozen_string_literal: true

RSpec.describe WbBotModelFallback::ForeignReasoning do
  fab!(:primary) { Fabricate(:llm_model, name: "primary-model") }
  fab!(:fallback) { Fabricate(:llm_model, name: "fallback-model") }
  fab!(:user)
  fab!(:bot_user, :user)
  fab!(:pm) do
    Fabricate(
      :private_message_topic,
      user: user,
      topic_allowed_users: [
        Fabricate.build(:topic_allowed_user, user: user),
        Fabricate.build(:topic_allowed_user, user: bot_user),
      ],
    )
  end
  fab!(:first_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 1,
      raw: "Первый вопрос",
      created_at: 10.minutes.ago,
    )
  end
  fab!(:primary_answer) do
    Fabricate(
      :post,
      topic: pm,
      user: bot_user,
      post_number: 2,
      raw: "Ответ основной",
      created_at: 9.minutes.ago,
    )
  end
  fab!(:second_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 3,
      raw: "Второй вопрос",
      created_at: 8.minutes.ago,
    )
  end
  fab!(:fallback_answer) do
    Fabricate(
      :post,
      topic: pm,
      user: bot_user,
      post_number: 4,
      raw: "Ответ запасной",
      created_at: 7.minutes.ago,
    )
  end
  fab!(:third_question) do
    Fabricate(
      :post,
      topic: pm,
      user: user,
      post_number: 5,
      raw: "Третий вопрос",
      created_at: 6.minutes.ago,
    )
  end

  # настоящая цепочка Responses API: рассуждение, вызов инструмента с идентификатором fc_…,
  # результат инструмента и текст ответа
  def remember_model(post, model, text, encrypted, call:)
    post.custom_fields[DiscourseAi::AiBot::POST_AI_LLM_MODEL_ID_FIELD] = model.id
    post.save_custom_fields
    PostCustomPrompt.create!(
      post: post,
      custom_prompt: [
        [
          { name: "search", arguments: { query: "реле" } }.to_json,
          "call_#{call}",
          "tool_call",
          "search",
          {
            "message" => "рассуждение",
            "provider_info" => {
              "open_ai_responses" => {
                "reasoning_id" => "rs_#{encrypted}",
                "encrypted_content" => encrypted,
              },
            },
          },
          { "open_ai_responses" => { "id" => call } },
        ],
        [{ result: "найдено" }.to_json, "call_#{call}", "tool", "search"],
        [text, bot_user.username, nil, nil],
      ],
    )
  end

  before do
    enable_current_plugin
    SiteSetting.wb_bot_model_fallback_llm = fallback.id.to_s
    remember_model(primary_answer, primary, "Ответ основной", "enc-primary", call: "fc_primary")
    remember_model(fallback_answer, fallback, "Ответ запасной", "enc-fallback", call: "fc_fallback")
  end

  def history
    DiscourseAi::Completions::PromptMessagesBuilder.messages_from_post(
      third_question,
      max_posts: 10,
      bot_usernames: [bot_user.username],
      include_uploads: false,
    )
  end

  def encrypted(messages)
    messages.filter_map do |message|
      message.dig(:thinking_provider_info, :open_ai_responses, :encrypted_content)
    end
  end

  def call_ids(messages)
    messages.filter_map { |message| message.dig(:provider_data, :open_ai_responses, :id) }
  end

  it "keeps all reasoning outside of a bot reply" do
    expect(encrypted(history)).to contain_exactly("enc-primary", "enc-fallback")
  end

  it "drops reasoning of posts generated by the primary model when answering with the fallback" do
    expect(encrypted(described_class.with_model(fallback.id) { history })).to eq(["enc-fallback"])
  end

  it "drops reasoning of the fallback model when answering with the primary again" do
    expect(encrypted(described_class.with_model(primary.id) { history })).to eq(["enc-primary"])
  end

  it "keeps the text of the answers whose reasoning was dropped" do
    text =
      described_class.with_model(fallback.id) { history }.map { |m| m[:content].to_s }.join("\n")
    expect(text).to include("Ответ основной", "Ответ запасной")
  end

  it "keeps tool call ids of all posts outside of a bot reply" do
    expect(call_ids(history)).to contain_exactly("fc_primary", "fc_fallback")
  end

  it "drops tool call ids of the primary model when answering with the fallback, keeping the calls" do
    messages = described_class.with_model(fallback.id) { history }
    expect(call_ids(messages)).to eq(["fc_fallback"])
    expect(messages.select { |m| m[:type] == :tool_call }.map { |m| m[:id] }).to contain_exactly(
      "call_fc_primary",
      "call_fc_fallback",
    )
  end

  it "drops tool call ids of the fallback model when answering with the primary again" do
    expect(call_ids(described_class.with_model(primary.id) { history })).to eq(["fc_primary"])
  end

  it "treats old bot posts without the model field as foreign only for the fallback model" do
    PostCustomField.where(
      post_id: primary_answer.id,
      name: DiscourseAi::AiBot::POST_AI_LLM_MODEL_ID_FIELD,
    ).delete_all

    expect(call_ids(described_class.with_model(fallback.id) { history })).to eq(["fc_fallback"])
    expect(encrypted(described_class.with_model(fallback.id) { history })).to eq(["enc-fallback"])
    expect(call_ids(described_class.with_model(primary.id) { history })).to eq(["fc_primary"])
  end

  it "restores the thread state after the block" do
    described_class.with_model(fallback.id) { history }
    expect(Thread.current[described_class::CURRENT_MODEL]).to be_nil
    expect(Thread.current[described_class::FOREIGN_STAMPS]).to be_nil
  end
end
